const config = require('./src/utils/siteConfig')

module.exports = {
  siteMetadata: {
    siteUrl: config.siteUrl,
    title: config.siteTitle,
    description: config.Description,
    author: config.Author,
    twitter: config.Twitter,
    facebook: config.fbAppID,
    organization: config.Organization,
    canonicalUrl: config.canonicalUrl,
    image: config.Image,
    navigation: [
      { text: 'All', href: '/' },
      { text: '3D', href: '/3d' },
      { text: 'Agency', href: '/agency' },
      { text: 'Articles', href: '/article' },
      { text: 'Backgrounds', href: '/background' },
      { text: 'Books', href: '/book' },
      { text: 'Colors', href: '/color' },
      { text: 'Conferences', href: '/conference' },
      { text: 'Design System', href: '/designsystem' },
      { text: 'Design Tools', href: '/tool' },
      { text: 'Fonts', href: '/font' },
      { text: 'Gradients', href: '/gradient' },
      { text: 'Handoff', href: '/handoff' },
      { text: 'Icons', href: '/icon' },
      { text: 'Illustrations', href: '/illustration' },
      { text: 'Inspirations', href: '/inspiration' },
      { text: 'Library', href: '/library' },
      { text: 'Mockups', href: '/mockup' },
      { text: 'Motion', href: '/motion' },
      { text: 'News', href: '/news' },
      { text: 'Newsletters', href: '/newsletter' },
      { text: 'Online Courses', href: '/onlinecourse' },
      { text: 'Photos', href: '/photo' },
      { text: 'Podcasts', href: '/podcast' },
      { text: 'Portfolios', href: '/portfolio' },
      { text: 'Prototypes', href: '/prototype' },
      { text: 'Resources', href: '/resource' },
      { text: 'Sounds', href: '/sound' },
      { text: 'Teams', href: '/team' },
      { text: 'Video Courses', href: '/videocourse' },
      { text: 'Web Design', href: '/web' },
      { text: 'WeChat', href: '/wechat' },
      { text: 'Wireframes', href: '/wireframe' },
    ],
  },
  plugins: [
    'gatsby-plugin-styled-components',
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-subfont',
    // 'gatsby-plugin-robots-txt',
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `./src/data/`,
      },
    },
    'gatsby-transformer-yaml',
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: 'UA-101495671-2',
        head: false
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/static/images/`,
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: config.siteTitle,
        short_name: config.shortTitle,
        description: config.Description,
        start_url: '/',
        background_color: config.backgroundColor,
        theme_color: config.themeColor,
        display: "standalone",
        icon: `static/images${config.siteLogo}`
      },
    },
    `gatsby-plugin-advanced-sitemap`,
    'gatsby-plugin-offline',
    'gatsby-plugin-netlify',
  ],
}
