module.exports = {
  siteTitle: 'DEX.List - The Index page for digital designers.',
  Publisher: 'DEX Group',
  Description: 'The index page for digital designers.',
  siteUrl: 'https://dexlist.page/',
  Author: '@dingyi',
  AuthorUrl: 'https://ding.one/',
  Organization: {
    name: 'DEX Group',
    url: 'https://dex.group/',
    logo: '/static/images/favicon.png',
  },
  canonicalUrl: 'https://dexlist.page/',
  Image: '/static/images/share.jpg',
  Twitter: '@dexgroup',
  fbAppID: '',
  shortTitle: 'DEX.List',
  shareImage: '/static/images/share.jpg',
  shareImageWidth: 900,
  shareImageHeight: 600,
  siteLogo: '/static/images/favicon.png',
  backgroundColor: '#fdf3f6',
  themeColor: '#F7417A',
  copyright: 'Copyright © 2019 DEX Group Inc',
}
